export enum TelegramMethodEnum {
    GetMe = "getMe",
    GetUpdates = "getUpdates",
    SendText = "sendMessage",
    SendMessage = "sendMessage",
    SendAudio = "sendAudio",
    DeleteMessage = "deleteMessage",
    EditMessageText = "editMessageText",
    EditText = "editMessageText",
    AnswerCallbackQuery = "answerCallbackQuery",
    AnswerInlineQuery = "answerInlineQuery",
    EditMessageReplyMarkup = "editMessageReplyMarkup",
    ForwardMessage = "forwardMessage",
    CopyMessage = "copyMessage",
    SendChatAction = "sendChatAction",
    LeaveChat = "leaveChat",
    SetWebhook = "setWebhook",
};
